### ISSUE TITLE
Fix github windows package build

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#763]
```
Run make package
  make package
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    VERSION: 1.4.[2](https://github.com/cxong/cdogs-sdl/actions/runs/4947636456/jobs/8847285398#step:16:2)
    CTEST_EXT_COLOR_OUTPUT: true
    CTEST_OUTPUT_ON_FAILURE: 1
    CTEST_BUILD_FLAGS: -j4
    BUILD_TYPE: Release
    SDL_AUDIODRIVER: dummy
    SDL_VIDEODRIVER: dummy
mingw[3](https://github.com/cxong/cdogs-sdl/actions/runs/4947636456/jobs/8847285398#step:16:3)2-make: *** No rule to make target 'package'.  Stop.
```
Need to use cmake instead of make in workflow step
